-- AlterTable "Vehicle"
ALTER TABLE "Vehicle" ADD COLUMN "type" TEXT DEFAULT 'Bus',
ADD COLUMN "subtitle" TEXT,
ADD COLUMN "description" TEXT,
ADD COLUMN "history" TEXT,
ADD COLUMN "isPublic" BOOLEAN DEFAULT false,
ADD COLUMN "immat" TEXT,
ADD COLUMN "numerosFlotte" TEXT,
ADD COLUMN "constructeur" TEXT,
ADD COLUMN "energie" TEXT,
ADD COLUMN "miseEnCirculation" TIMESTAMP(3),
ADD COLUMN "longueur" TEXT,
ADD COLUMN "placesAssises" INTEGER,
ADD COLUMN "placesDebout" INTEGER,
ADD COLUMN "ufr" TEXT,
ADD COLUMN "moteur" TEXT,
ADD COLUMN "boiteVitesses" TEXT,
ADD COLUMN "nombrePortes" INTEGER,
ADD COLUMN "climatisation" TEXT,
ADD COLUMN "girouette" TEXT,
ADD COLUMN "normeEuro" TEXT,
ADD COLUMN "livree" TEXT,
ADD COLUMN "statut" TEXT,
ADD COLUMN "preservePar" TEXT;
